routingRules:
  - domain: "beckn.one:deg:ev-charging:2.0.0"  # Retail domain
    version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support

  - domain: "beckn.one:deg:ev-charging:2.0.0"  # Retail domain
    version: "2.0.0"
    targetType: "url"
    target: # URL of Catalog Discovery Service
      url: "https://FILL_ME_CATALOG_DISCOVERY_SERVICE_URL/beckn"
    endpoints:
      - discover
